version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coupon_wallet
    volumes:
      - coupon-wallet_postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  coupon-wallet_postgres-data:  # Add the volume declaration here
